package project.bangunruang.view;

import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import project.bangundatar.view.Segitiga;
import project.bangunruang.controller.CLimasSegiEmpat;
import project.bangunruang.controller.CLimasSegitiga;
import project.main.MainMenu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Catur Rahmat
 */
public class Limas extends javax.swing.JFrame {

    /**
     * Creates new form Square
     */
    public Limas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Limas = new javax.swing.ButtonGroup();
        PersegiPanjang = new javax.swing.JPanel();
        LblMassukanLAlas = new javax.swing.JLabel();
        IAlasOrSisi = new javax.swing.JTextField();
        BtnReset = new javax.swing.JButton();
        BtnHitung = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        LblMassukanTinggiAlas = new javax.swing.JLabel();
        ITinggiAlas = new javax.swing.JTextField();
        LblVolume = new javax.swing.JLabel();
        LblLuasPermukaan = new javax.swing.JLabel();
        OVolume = new javax.swing.JTextField();
        OLuasPermukaan = new javax.swing.JTextField();
        LblHasil = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NetbeansLogo = new javax.swing.JLabel();
        JavaLogo = new javax.swing.JLabel();
        CaturRahmat = new javax.swing.JLabel();
        YoffanAlfiatur = new javax.swing.JLabel();
        AlexMasrobi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PoweredBy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RSegitiga = new javax.swing.JRadioButton();
        RPersegi = new javax.swing.JRadioButton();
        ITinggi = new javax.swing.JTextField();
        LblMassukanTinggiLimas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PersegiPanjang.setBackground(new java.awt.Color(0, 231, 0));
        PersegiPanjang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "KALKULATOR LIMAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        PersegiPanjang.setFocusable(false);
        PersegiPanjang.setRequestFocusEnabled(false);
        PersegiPanjang.setVerifyInputWhenFocusTarget(false);

        LblMassukanLAlas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblMassukanLAlas.setText("Massukan Sisi/Alas");

        if(RSegitiga.isSelected() || RPersegi.isSelected()){
            IAlasOrSisi.setEditable(true);
        }
        IAlasOrSisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IAlasOrSisiActionPerformed(evt);
            }
        });

        BtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Clear-icon.png"))); // NOI18N
        BtnReset.setText("  Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/calculator-icon.png"))); // NOI18N
        BtnHitung.setText("Hitung");
        BtnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitungActionPerformed(evt);
            }
        });

        BtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Go-back-icon.png"))); // NOI18N
        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        LblMassukanTinggiAlas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblMassukanTinggiAlas.setText("Massukan Tinggi Alas");

        ITinggiAlas.setAutoscrolls(false);
        ITinggiAlas.setFocusTraversalPolicyProvider(true);
        ITinggiAlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITinggiAlasActionPerformed(evt);
            }
        });

        LblVolume.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblVolume.setText("Volume");

        LblLuasPermukaan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblLuasPermukaan.setText("Luas Permukaan");

        OVolume.setEditable(false);
        OVolume.setBackground(new java.awt.Color(204, 204, 204));
        OVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OVolumeActionPerformed(evt);
            }
        });

        OLuasPermukaan.setEditable(false);
        OLuasPermukaan.setBackground(new java.awt.Color(204, 204, 204));
        OLuasPermukaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OLuasPermukaanActionPerformed(evt);
            }
        });

        LblHasil.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        LblHasil.setForeground(new java.awt.Color(255, 255, 255));
        LblHasil.setText("HASIL PERHITUNGAN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        NetbeansLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/netbeans-icon.png"))); // NOI18N

        JavaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Java-icon.png"))); // NOI18N

        CaturRahmat.setText("Catur Rahmat 124180026");

        YoffanAlfiatur.setText("Yoffan Alfiatur R 124180025");

        AlexMasrobi.setText("Alex Masrobi 124180029");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Upnlogo.jpg"))); // NOI18N

        PoweredBy.setText("Created by :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PoweredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CaturRahmat)
                .addGap(80, 80, 80)
                .addComponent(YoffanAlfiatur)
                .addGap(89, 89, 89)
                .addComponent(AlexMasrobi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NetbeansLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JavaLogo)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JavaLogo))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CaturRahmat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YoffanAlfiatur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(AlexMasrobi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PoweredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(NetbeansLogo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Filesystem-blockdevice-cubes-icon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/rsz_2karkulator.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/rsz_logo_upn.png"))); // NOI18N

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/objects-icon.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        Limas.add(RSegitiga);
        RSegitiga.setText("Segitiga");

        Limas.add(RPersegi);
        RPersegi.setText("Persegi");

        ITinggi.setAutoscrolls(false);
        ITinggi.setFocusTraversalPolicyProvider(true);
        ITinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITinggiActionPerformed(evt);
            }
        });

        LblMassukanTinggiLimas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblMassukanTinggiLimas.setText("Massukan Tinggi Limas");

        javax.swing.GroupLayout PersegiPanjangLayout = new javax.swing.GroupLayout(PersegiPanjang);
        PersegiPanjang.setLayout(PersegiPanjangLayout);
        PersegiPanjangLayout.setHorizontalGroup(
            PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblVolume, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblLuasPermukaan, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(37, 37, 37))
                            .addComponent(LblMassukanTinggiLimas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(OLuasPermukaan, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                                            .addComponent(OVolume)))
                                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(IAlasOrSisi, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                                            .addComponent(ITinggiAlas)
                                            .addComponent(ITinggi))))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersegiPanjangLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersegiPanjangLayout.createSequentialGroup()
                                        .addComponent(LblHasil)
                                        .addGap(376, 376, 376))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersegiPanjangLayout.createSequentialGroup()
                                        .addComponent(BtnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(304, 304, 304)
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27))))))
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMassukanLAlas)
                            .addComponent(LblMassukanTinggiAlas))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Icon)
                        .addGap(208, 208, 208)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30))))
            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(RSegitiga)
                .addGap(239, 239, 239)
                .addComponent(RPersegi)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PersegiPanjangLayout.setVerticalGroup(
            PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Icon))
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMassukanLAlas)
                    .addComponent(IAlasOrSisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMassukanTinggiAlas)
                    .addComponent(ITinggiAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ITinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMassukanTinggiLimas))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RSegitiga)
                            .addComponent(RPersegi))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addComponent(BtnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblHasil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblVolume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OLuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblLuasPermukaan))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PersegiPanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IAlasOrSisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IAlasOrSisiActionPerformed
        
    }//GEN-LAST:event_IAlasOrSisiActionPerformed

    private void ITinggiAlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITinggiAlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ITinggiAlasActionPerformed

    private void OVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OVolumeActionPerformed
        
    }//GEN-LAST:event_OVolumeActionPerformed

    private void OLuasPermukaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OLuasPermukaanActionPerformed
        
    }//GEN-LAST:event_OLuasPermukaanActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
    //Btn Reset
    IAlasOrSisi.setText(" ");
    ITinggi.setText(" ");
    ITinggiAlas.setText(" ");
    OVolume.setText(" ");
    OLuasPermukaan.setText(" ");
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
    //BtnBack
    MainMenu menu;
    menu = new MainMenu();
    menu.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitungActionPerformed
     if(RSegitiga.isSelected()){
          try{   
        String TmpAlasOrSisi = IAlasOrSisi.getText();
        double alas = Double.parseDouble(TmpAlasOrSisi);
        String TmpTinggi = ITinggiAlas.getText();
        double tinggi = Double.parseDouble(TmpTinggi);
        String TmpTinggiSegitiga = ITinggiAlas.getText();
        double tinggiSegitiga = Double.parseDouble(TmpTinggiSegitiga);
        CLimasSegitiga cLimasSegitiga = new CLimasSegitiga(alas,tinggiSegitiga,tinggi);
        cLimasSegitiga.volume();
        cLimasSegitiga.luasPermukaan();
        double TmpVolume = cLimasSegitiga.getVolume();   
        String volume = Double.toString(TmpVolume);
        OVolume.setText(volume);
        double TmpLuasPermukaan = cLimasSegitiga.getLuasPermukaan();   
        String luasPermukaan = Double.toString(TmpLuasPermukaan);
        OLuasPermukaan.setText(luasPermukaan);
        }catch (NumberFormatException check1){
            JOptionPane.showMessageDialog(this, "Input Salah, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
            IAlasOrSisi.setText(" ");
            ITinggiAlas.setText(" ");
            ITinggi.setText(" ");
            OLuasPermukaan.setText(" ");
            OVolume.setText(" ");
        }
        catch (InputMismatchException check2){
            JOptionPane.showMessageDialog(this, "Input Melebihi Max, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
            IAlasOrSisi.setText(" ");
            ITinggiAlas.setText(" ");
            ITinggi.setText(" ");
            OLuasPermukaan.setText(" ");
            OVolume.setText(" ");
        }
     }else if ((RPersegi.isSelected())){
        try{
        ITinggiAlas.setText(" ");
        String TmpAlasOrSisi = IAlasOrSisi.getText();
        double alas = Double.parseDouble(TmpAlasOrSisi);
        String TmpTinggi = ITinggi.getText();
        double tinggi = Double.parseDouble(TmpTinggi);
        CLimasSegiEmpat cLimasPersegi = new CLimasSegiEmpat(alas,tinggi);
        cLimasPersegi.volume();
        cLimasPersegi.luasPermukaan();
        double TmpVolume = cLimasPersegi.getVolume();   
        String volume = Double.toString(TmpVolume);
        OVolume.setText(volume);
        double TmpLuasPermukaan = cLimasPersegi.getLuasPermukaan();   
        String luasPermukaan = Double.toString(TmpLuasPermukaan);
        OLuasPermukaan.setText(luasPermukaan);
        }catch (NumberFormatException check1){
            JOptionPane.showMessageDialog(this, "Input Salah, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
            IAlasOrSisi.setText(" ");
            ITinggi.setText(" ");
            OLuasPermukaan.setText(" ");
            OVolume.setText(" ");
        }
        catch (InputMismatchException check2){
            JOptionPane.showMessageDialog(this, "Input Melebihi Max, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
            IAlasOrSisi.setText(" ");
            ITinggi.setText(" ");
            OLuasPermukaan.setText(" ");
            OVolume.setText(" ");
        }
         
     }
    }//GEN-LAST:event_BtnHitungActionPerformed

    private void ITinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ITinggiActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Limas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlexMasrobi;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnHitung;
    private javax.swing.JButton BtnReset;
    private javax.swing.JLabel CaturRahmat;
    private javax.swing.JTextField IAlasOrSisi;
    private javax.swing.JTextField ITinggi;
    private javax.swing.JTextField ITinggiAlas;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel JavaLogo;
    private javax.swing.JLabel LblHasil;
    private javax.swing.JLabel LblLuasPermukaan;
    private javax.swing.JLabel LblMassukanLAlas;
    private javax.swing.JLabel LblMassukanTinggiAlas;
    private javax.swing.JLabel LblMassukanTinggiLimas;
    private javax.swing.JLabel LblVolume;
    private javax.swing.ButtonGroup Limas;
    private javax.swing.JLabel NetbeansLogo;
    private javax.swing.JTextField OLuasPermukaan;
    private javax.swing.JTextField OVolume;
    private javax.swing.JPanel PersegiPanjang;
    private javax.swing.JLabel PoweredBy;
    private javax.swing.JRadioButton RPersegi;
    private javax.swing.JRadioButton RSegitiga;
    private javax.swing.JLabel YoffanAlfiatur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
