package project.bangunruang.view;

import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import project.bangunruang.controller.CPrismaSegiEmpat;
import project.bangunruang.controller.CPrismaSegitiga;
import project.bangunruang.controller.CPrismaJajarGenjang;
import project.bangunruang.controller.CPrismaTrapesium;
import project.main.MainMenu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Catur Rahmat
 */
public class Prisma extends javax.swing.JFrame {

    /**
     * Creates new form Square
     */
    public Prisma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prisma = new javax.swing.ButtonGroup();
        PersegiPanjang = new javax.swing.JPanel();
        LblMassukanSisi1 = new javax.swing.JLabel();
        ISisi1 = new javax.swing.JTextField();
        BtnReset = new javax.swing.JButton();
        BtnCount = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        LblMassukanTinggiPrisma = new javax.swing.JLabel();
        LblVolume = new javax.swing.JLabel();
        LblLuasPermukaan = new javax.swing.JLabel();
        OVolume = new javax.swing.JTextField();
        OLuasPermukaan = new javax.swing.JTextField();
        LblHasil = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NetbeansLogo = new javax.swing.JLabel();
        JavaLogo = new javax.swing.JLabel();
        CaturRahmat = new javax.swing.JLabel();
        YoffanAlfiatur = new javax.swing.JLabel();
        AlexMasrobi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PoweredBy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblMassukanTinggi = new javax.swing.JLabel();
        ISisi2 = new javax.swing.JTextField();
        Icon = new javax.swing.JLabel();
        RSegitiga = new javax.swing.JRadioButton();
        RTrapesium = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        RSegiEmpat = new javax.swing.JRadioButton();
        ITinggiPrisma = new javax.swing.JTextField();
        ISisiMiring = new javax.swing.JTextField();
        LblMassukanTinggiPrisma1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PersegiPanjang.setBackground(new java.awt.Color(0, 231, 0));
        PersegiPanjang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "KALKULATOR PRISMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        PersegiPanjang.setFocusable(false);
        PersegiPanjang.setRequestFocusEnabled(false);
        PersegiPanjang.setVerifyInputWhenFocusTarget(false);

        LblMassukanSisi1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblMassukanSisi1.setText("Alas/Jari-Jari1/Sisi 1");

        ISisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISisi1ActionPerformed(evt);
            }
        });

        BtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Clear-icon.png"))); // NOI18N
        BtnReset.setText("  Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/calculator-icon.png"))); // NOI18N
        BtnCount.setText("Hitung");
        BtnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCountActionPerformed(evt);
            }
        });

        BtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Go-back-icon.png"))); // NOI18N
        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        LblMassukanTinggiPrisma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblMassukanTinggiPrisma.setText("Massukan Tinggi P ");

        LblVolume.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblVolume.setText("Volume");

        LblLuasPermukaan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblLuasPermukaan.setText("Luas Permukaan");

        OVolume.setEditable(false);
        OVolume.setBackground(new java.awt.Color(204, 204, 204));
        OVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OVolumeActionPerformed(evt);
            }
        });

        OLuasPermukaan.setEditable(false);
        OLuasPermukaan.setBackground(new java.awt.Color(204, 204, 204));
        OLuasPermukaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OLuasPermukaanActionPerformed(evt);
            }
        });

        LblHasil.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        LblHasil.setForeground(new java.awt.Color(255, 255, 255));
        LblHasil.setText("HASIL PERHITUNGAN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        NetbeansLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/netbeans-icon.png"))); // NOI18N

        JavaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Java-icon.png"))); // NOI18N

        CaturRahmat.setText("Catur Rahmat 124180026");

        YoffanAlfiatur.setText("Yoffan Alfiatur R 124180025");

        AlexMasrobi.setText("Alex Masrobi 124180029");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Upnlogo.jpg"))); // NOI18N

        PoweredBy.setText("Created by : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PoweredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CaturRahmat)
                .addGap(80, 80, 80)
                .addComponent(YoffanAlfiatur)
                .addGap(89, 89, 89)
                .addComponent(AlexMasrobi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NetbeansLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JavaLogo)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JavaLogo))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CaturRahmat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YoffanAlfiatur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(AlexMasrobi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PoweredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(NetbeansLogo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/Filesystem-blockdevice-cubes-icon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/rsz_2karkulator.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/rsz_logo_upn.png"))); // NOI18N

        LblMassukanTinggi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblMassukanTinggi.setText("Tinggi/Jari-Jari2/Sisi 2");

        ISisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISisi2ActionPerformed(evt);
            }
        });

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/img/img/objects-icon.png"))); // NOI18N

        Prisma.add(RSegitiga);
        RSegitiga.setText("Segitiga");
        RSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSegitigaActionPerformed(evt);
            }
        });

        Prisma.add(RTrapesium);
        RTrapesium.setText("Trapesium");

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        Prisma.add(RSegiEmpat);
        RSegiEmpat.setText("Trapesium Terpancung");

        ITinggiPrisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITinggiPrismaActionPerformed(evt);
            }
        });

        ISisiMiring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISisiMiringActionPerformed(evt);
            }
        });

        LblMassukanTinggiPrisma1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblMassukanTinggiPrisma1.setText("Massukan Sisi M ");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*Mohon Input Menyesuaikan Dengan Field Yang Tersedia");

        javax.swing.GroupLayout PersegiPanjangLayout = new javax.swing.GroupLayout(PersegiPanjang);
        PersegiPanjang.setLayout(PersegiPanjangLayout);
        PersegiPanjangLayout.setHorizontalGroup(
            PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addComponent(LblMassukanTinggi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblLuasPermukaan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblVolume, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMassukanTinggiPrisma, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMassukanTinggiPrisma1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMassukanSisi1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(OLuasPermukaan, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                                                    .addComponent(OVolume)))
                                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                                        .addGap(264, 264, 264)
                                                        .addComponent(BtnCount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(274, 336, Short.MAX_VALUE))
                                                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(ISisiMiring, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(ISisi1, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(ISisi2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                                                            .addComponent(ITinggiPrisma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                                        .addGap(44, 44, 44))
                                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(RSegitiga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32))
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Icon)
                                .addGap(246, 246, 246)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersegiPanjangLayout.createSequentialGroup()
                .addContainerGap(648, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addComponent(RSegiEmpat)
                        .addGap(120, 120, 120)
                        .addComponent(RTrapesium))
                    .addComponent(LblHasil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PersegiPanjangLayout.setVerticalGroup(
            PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersegiPanjangLayout.createSequentialGroup()
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Icon))
                    .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMassukanSisi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMassukanTinggi)
                    .addComponent(ISisi2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMassukanTinggiPrisma)
                    .addComponent(ITinggiPrisma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISisiMiring, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMassukanTinggiPrisma1))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RTrapesium)
                    .addComponent(RSegiEmpat)
                    .addComponent(RSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersegiPanjangLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BtnCount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersegiPanjangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblHasil)
                .addGap(7, 7, 7)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblVolume))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OLuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblLuasPermukaan))
                .addGap(18, 18, 18)
                .addGroup(PersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PersegiPanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ISisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISisi1ActionPerformed
        
    }//GEN-LAST:event_ISisi1ActionPerformed

    private void OVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OVolumeActionPerformed
        
    }//GEN-LAST:event_OVolumeActionPerformed

    private void OLuasPermukaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OLuasPermukaanActionPerformed
        
    }//GEN-LAST:event_OLuasPermukaanActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
    //Btn Reset
    ISisi2.setText(" ");
    ISisi1.setText(" ");
    ISisiMiring.setText(" ");
    ITinggiPrisma.setText(" ");
    OVolume.setText(" ");
    OLuasPermukaan.setText(" ");
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
    //BtnBack
    MainMenu menu;
    menu = new MainMenu();
    menu.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_BtnBackActionPerformed

    private void ISisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISisi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISisi2ActionPerformed

    private void BtnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCountActionPerformed
    if(RSegitiga.isSelected()){
        ISisiMiring.setText(" ");
          try{   
        String TmpAlas = ISisi1.getText();
        double alas = Double.parseDouble(TmpAlas);
        String TmpTinggi = ISisi2.getText();
        double tinggi = Double.parseDouble(TmpTinggi);
        String TmpTinggiPrisma = ITinggiPrisma.getText();
        double tinggiPrisma = Double.parseDouble(TmpTinggiPrisma);
        CPrismaSegitiga cPrismaSegitiga = new CPrismaSegitiga(alas,tinggi,tinggiPrisma);
        cPrismaSegitiga.volume();
        cPrismaSegitiga.luasPermukaan();
        double TmpVolume = cPrismaSegitiga.getVolume();   
        String volume = Double.toString(TmpVolume);
        OVolume.setText(volume);
        double TmpLuasPermukaan = cPrismaSegitiga.getLuasPermukaan();   
        String luasPermukaan = Double.toString(TmpLuasPermukaan);
        OLuasPermukaan.setText(luasPermukaan);
        }catch (NumberFormatException check1){
            JOptionPane.showMessageDialog(this, "Input Salah, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
                ITinggiPrisma.setText(" ");
    ISisi2.setText(" ");
    ISisi1.setText(" ");
    OVolume.setText(" ");
    OLuasPermukaan.setText(" ");
        }
        catch (InputMismatchException check2){
            JOptionPane.showMessageDialog(this, "Input Melebihi Max, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
                ITinggiPrisma.setText(" ");
    ISisi2.setText(" ");
    ISisi1.setText(" ");
    OVolume.setText(" ");
    OLuasPermukaan.setText(" ");
        }
     }else if(RTrapesium.isSelected()){
      
         try{   
        String TmpSisi1 = ISisi1.getText();
        double sisi1 = Double.parseDouble(TmpSisi1);
        String TmpSisi2 = ISisi2.getText();
        double sisi2 = Double.parseDouble(TmpSisi2);
        String TmpTinggiPrisma = ITinggiPrisma.getText();
        double tinggiPrisma = Double.parseDouble(TmpTinggiPrisma);
        String TmpSisiMiring = ISisiMiring.getText();
        double sisiMiring = Double.parseDouble(TmpSisiMiring);
        CPrismaTrapesium cPrismaTrapesium = new CPrismaTrapesium(sisi1,sisi2,tinggiPrisma,sisiMiring);
        cPrismaTrapesium.volume();
        cPrismaTrapesium.luasPermukaan();
        double TmpVolume = cPrismaTrapesium.getVolume();   
        String volume = Double.toString(TmpVolume);
        OVolume.setText(volume);
        double TmpLuasPermukaan = cPrismaTrapesium.getLuasPermukaan();   
        String luasPermukaan = Double.toString(TmpLuasPermukaan);
        OLuasPermukaan.setText(luasPermukaan);
        }catch (NumberFormatException check1){
            JOptionPane.showMessageDialog(this, "Input Salah, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
                ISisi1.setText(" ");
    ISisiMiring.setText(" ");
    ITinggiPrisma.setText(" ");
    OVolume.setText(" ");
    OLuasPermukaan.setText(" ");
        }
        catch (InputMismatchException check2){
            JOptionPane.showMessageDialog(this, "Input Melebihi Max, Please Try Again","ERROR!!!",JOptionPane.WARNING_MESSAGE);
                ISisi1.setText(" ");
    ISisiMiring.setText(" ");
    ITinggiPrisma.setText(" ");
    OVolume.setText(" ");
    OLuasPermukaan.setText(" ");
        }
     }
    }//GEN-LAST:event_BtnCountActionPerformed

    private void ITinggiPrismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITinggiPrismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ITinggiPrismaActionPerformed

    private void ISisiMiringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISisiMiringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISisiMiringActionPerformed

    private void RSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSegitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Prisma().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlexMasrobi;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnCount;
    private javax.swing.JButton BtnReset;
    private javax.swing.JLabel CaturRahmat;
    private javax.swing.JTextField ISisi1;
    private javax.swing.JTextField ISisi2;
    private javax.swing.JTextField ISisiMiring;
    private javax.swing.JTextField ITinggiPrisma;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel JavaLogo;
    private javax.swing.JLabel LblHasil;
    private javax.swing.JLabel LblLuasPermukaan;
    private javax.swing.JLabel LblMassukanSisi1;
    private javax.swing.JLabel LblMassukanTinggi;
    private javax.swing.JLabel LblMassukanTinggiPrisma;
    private javax.swing.JLabel LblMassukanTinggiPrisma1;
    private javax.swing.JLabel LblVolume;
    private javax.swing.JLabel NetbeansLogo;
    private javax.swing.JTextField OLuasPermukaan;
    private javax.swing.JTextField OVolume;
    private javax.swing.JPanel PersegiPanjang;
    private javax.swing.JLabel PoweredBy;
    private javax.swing.ButtonGroup Prisma;
    private javax.swing.JRadioButton RSegiEmpat;
    private javax.swing.JRadioButton RSegitiga;
    private javax.swing.JRadioButton RTrapesium;
    private javax.swing.JLabel YoffanAlfiatur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
